name: Build the Unlocked Package

on:
  release:
    types: [published]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Install Salesforce CLI
        run: |
          node --version
          npm install @salesforce/cli --global
          sf update stable
          sf version
          sf plugins
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Say Hello
        run: echo "Hello World 🎉 The release event worked!"

      - name: "Authenticate Salesforce Dev Hub org"
        run: |
          echo "${{ secrets.DEVHUB_CERT_KEY }}" > server.key
          sf org login jwt \
            --client-id "3MVG9PwZx9R6_Urce3.53_goaHUSQhHZQC8Gk07lhPQ4Fxi4aJQzx0nadjm_PDmMw6OTiSf6QqGFDCrp0Bh.J" \
            --username "vitaliyarkhanhelski@curious-impala-7guxhs.com" \
            --jwt-key-file server.key \
            --set-default-dev-hub \
            --instance-url "https://login.salesforce.com" \
            --alias vitDevHub
