name: Build the Unlocked Package

on:
  release:
    types: [published]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Install Salesforce CLI
        run: |
          node --version
          npm install @salesforce/cli --global
          sf update stable
          sf version
          sf plugins
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Say Hello
        run: echo "Hello World 🎉 The release event worked!"

      - name: Authenticate to Salesforce
        run: |
            echo "Authenticating to Salesforce..."
            sf auth web --client-id 3MVG9PwZx9R6_Urce3.53_goaHUSQhHZQC8Gk07lhPQ4Fxi4aJQzx0nadjm_PDmMw6OTiSf6QqGFDCrp0Bh.J \
              --client-secret AD0DF8D1E700EB6BE1E026FBDBA889B86562E0F85C42C7A17B73FAA152BA1045 \
              --username "vitaliyarkhanhelski@curious-impala-7guxhs.com" \
              --password "SalesForce321!7ynDqv84tyyWUDppFe5evVJeq" \
              --instance-url "https://login.salesforce.com" \
              --set-default-username
#            sf auth web --clientid ${{ secrets.SF_CONSUMER_KEY }} \
#              --clientsecret ${{ secrets.SF_CONSUMER_SECRET }} \
#              --username ${{ secrets.SF_USERNAME }} \
#              --password ${{ secrets.SF_PASSWORD }} \
#              --instanceurl ${{ secrets.SF_LOGIN_URL }} \
#              --setdefaultusername
